### PR TITLE
feat: Friuli Venezia Giulia

### PR DESCRIPTION
**Pull request by FezVrasta**
I made a single PR as they all share the same website as source

### CODE REVIEW

**Comment by FezVrasta** [comment]
Could you merge this when you have time please?

**Comment by pirxpilot** [comment]
Please address/fix issues outlined in the review comments. Then squash the history and force push to PR branch.

**Comment by FezVrasta** [comment]
I don't see any comments, have you published them?

**Comment by pirxpilot** [comment]
> I don't see any comments, have you published them?

Yup. Not sure why you don't see them above. Any chance you somehow managed to collapse the comments? Direct link to review is [here](https://github.com/pirxpilot/liftie/pull/67/files/cfcec1c07f20df374940f1e607074c4a446c993e).

**Comment by FezVrasta** [comment]
No I can't see any comment. Could you send them again please?

**Comment by pirxpilot** [comment]
in: lib/tools/turismofvg.js
1. re: `toTitleCase` It's not needed: seems like the lift names are already properly capitalized in HTML.
2. re: `fn` It's not needed: 'close' and 'open' should be coerced automatically - pretty sure `fn` is not needed here

**Comment by FezVrasta** [comment]
done thanks

**Pull request merged**
