### PR TITLE
feat: Campo Felice

### PR DESCRIPTION
**Pull request by FezVrasta**

### CODE REVIEW

**Comment by pirxpilot** [comment]
There is something strange going on with certificate for this website. It seems to work OK in the browser but not when liftie/node or curl is used to fetch it.

```
curl -v https://www.campofelice.it/ita/impianti.php
*   Trying 195.110.124.188:443...
* TCP_NODELAY set
* Connected to www.campofelice.it (195.110.124.188) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
Maybe an intermediary cert in new and not in standard Linux CA yet?

**Comment by FezVrasta** [comment]
Could Liftie skip the SSL check maybe? It shouldn't matter for its purpose

**Comment by pirxpilot** [comment]
Yup. I've done that before - requires setting `NODE_TLS_REJECT_UNAUTHORIZED=0` - problem is it's an _all or nothing_ switch. And yes it should not matter, but I'd rather know what is specifically wrong in this case before we resort to that.

**Comment by pirxpilot** [comment]
This PR should not be marked as closed as merged (it's not as of yet) but GitHub seems to think it knows better... and I can't find a way to tell it otherwise.

**Comment by pirxpilot** [comment]
Looks like certificate chain returned by the server is incomplete:
```
1 | Sent by server | www.campofelice.it				 			 			
2 | Extra download | Thawte EV RSA CA G2
3 | In trust store | DigiCert Global Root G2
```
Node - differently from browsers does not download missing intermediary certs - see: nodejs/node#16336
Possible workaround: [node_extra_ca_certs_mozilla_bundle](https://github.com/arvind-agarwal/node_extra_ca_certs_mozilla_bundle) module

**Comment by pirxpilot** [comment]
Released as a part of 3.51.0
See: 1925e2ed26879d0056429c6df213c6a5cad9105f

**Pull request merged**
