### PR TITLE
Add Les Arcs as resort

### PR DESCRIPTION
**Pull request by mdjong1**

### CODE REVIEW

**Comment by pirxpilot** [comment]
Thanks! Looks like some tests for a newly added resort are failing. Some of that might be typos. Others look like skiplan parser issues. Could you check you can fix any of those?

**Comment by mdjong1** [comment]
That should do it

**Comment by pirxpilot** [comment]
This should be live now:
https://liftie.info/resort/lesarcs
Let me know if everything looks OK. Thanks again.

**Comment by mdjong1** [comment]
Looks perfect, thanks for the sweet project 👍

**Pull request closed without merging**
